version: '3.5' 

services: 
  frontend: 
    image: frontend:1.14
    ports:
      - 5000:5000
  backend:
    image: backend:1.14
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    ports:
      - 8080:8080
  redis:
    image: redis
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres