version: '3.5' 

services:
  training:
    image: ml-kurkkumopo-training
    volumes:
      - ./model:/src/model
      - ./imgs:/src/imgs
      - ./data:/data
  frontend:
    image: ml-kurkkumopo-frontend
    ports:
      - 3000:3000
  backend:
    image: ml-kurkkumopo-backend
    ports:
      - 5000:5000
    depends_on:
      - training
    volumes:
      - ./model:/src/model
