version: '3.5' 

services: 
  frontend: 
    image: frontend:1.14
  backend:
    image: backend:1.14
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
  redis:
    image: redis
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    environment:
      - NGINX_HOST=http://localhost
      - NGINX_PORT=80